In [80]:

import pandas as pd
df = pd.read_csv('acr_ac_scenarios.csv')
df.head()

,panel,scenario-id,scenario-text,scenario-url,sex,age,body-area,priority-clinical-areas
0,Breast,3110141,"Axillary adenopathy, breast cancer suspected",https://gravitas.acr.org/ACPortal/GetDataForOn...,Male Only,18 - 150,Breast,NaN
1,Breast,3194817,"Axillary lump, palpable, new, bilateral, initi...",https://gravitas.acr.org/ACPortal/GetDataForOn...,Female Only,18 - 150,Breast,NaN
2,Breast,3194815,"Axillary lump, palpable, new, unilateral, init...",https://gravitas.acr.org/ACPortal/GetDataForOn...,Female Only,18 - 150,Breast,NaN
3,Breast,3194837,"Axillary node, suspicious on imaging, not mamm...",https://gravitas.acr.org/ACPortal/GetDataForOn...,Female Only,18 - 150,Breast,NaN
4,Breast,3194835,"Axillary node, suspicious on mammo or US, next...",https://gravitas.acr.org/ACPortal/GetDataForOn...,Female Only,18 - 150,Breast,NaN

In [81]:
len(df)

3346

In [82]:
df['age'].unique()

array(['18 - 150', '25 - 150', '30 - 150', '40 - 150', '12 - 29',
       '30 - 39', '10 - 60', '40 - 60', '18 - 29', '0 - 24', '0 - 29',
       '0 - 17', '0 - 150', '45 - 150', '12 - 150', '5 - 150', '16 - 150',
       '18 - 49', '6 - 150', '10 - 150', '0 - 9', '65 - 150', '16 - 64',
       '50 - 150', '70 - 150', '80 - 150', '51 - 150', '0 - 7', '0 - 8',
       '66 - 150', '0 - 15', 'D90 - 6205', 'D0 - 729', '45339', '0 - 1',
       'D0 - 119', 'D181 - 6205', 'D120 - 180', 'D0 - 27', 'D28 - 119',
       'D0 - 179', 'D0 - 29', '45366', '0 - 3', '0 - 4', '45429',
       'D180 - 6205', '0 - 5', 'D0 - 30', 'D31 - 6205', '45582',
       'D30 - 1095', '45368', '0 - 2', 'D180 - 1825', 'D30 - 6205',
       'D0 - 28', 'D0 - 59', 'D60 - 2190', '45490', 'D0 - 2', 'D3 - 365',
       'D15 - 90', '50 - 80', '35 - 150', '18 - 39', '18-150'],
      dtype=object)

In [83]:
df['body-area'].unique()

array(['Breast', 'Cardiac-chest', 'Chest-abdomen-pelvis', 'Chest-abdomen',
       'Cardiac', 'Chest', 'cardiac-chest-pelvis', 'Abdomen-pelvis',
       'Abdomen', 'Pelvis', 'Neck-chest', 'Unspecified', 'Extremities',
       'Spine', 'Lower extremity', 'Upper extremity', 'Spine-pelvis',
       'Head', 'Neck', 'Head-neck', 'Maxface', 'Head-spine'], dtype=object)

In [84]:

filtered_df = df[df['body-area'].isin(['Chest-abdomen', 'Abdomen-pelvis', 'Abdomen', 'Pelvis'])]
body_area_n = len(filtered_df)
print(body_area_n)

613

In [85]:
filtered_df = filtered_df[filtered_df['panel'] != 'Pediatric']
without_peds_n = len(filtered_df)
print(without_peds_n)

555

In [86]:

filtered_df = filtered_df[~filtered_df['scenario-text'].str.contains('pregnant', case=False, na=False)]
without_pregnant_n = len(filtered_df)
print(without_pregnant_n)

540

In [87]:
filtered_df = filtered_df[filtered_df['panel'] != 'Interventional Radiology']
without_IR_n = len(filtered_df)
print(without_IR_n)

502

In [88]:
pattern_list = ['staging', 
                'screen', 
                'surveillance',
                'incidental finding',
                'imaging during treatment',
                'posttreatment imaging',
                'post treatment imaging',
                'preop planning',
                'pre-op planning'
                ]

pattern = '|'.join(pattern_list)
filtered_df = filtered_df[~filtered_df['scenario-text'].str.contains(pattern, case=False, na=False)]
without_monitoring_n = len(filtered_df)
print(without_monitoring_n)

391

In [89]:
removed_pelvis_df = filtered_df[filtered_df['body-area'] == 'Pelvis']
filtered_df = filtered_df[filtered_df['body-area'] != 'Pelvis']
without_pelvis_n = len(filtered_df)
print(without_pelvis_n)

205

In [90]:

# Find duplicate scenario texts
duplicate_scenarios = filtered_df[filtered_df.duplicated(subset=['scenario-text'], keep=False)]
duplicate_scenarios = duplicate_scenarios.sort_values('scenario-text')
print(f"Found {len(duplicate_scenarios)} rows with duplicate scenarios")
display(duplicate_scenarios)

Found 36 rows with duplicate scenarios

,panel,scenario-id,scenario-text,scenario-url,sex,age,body-area,priority-clinical-areas
184,Cardiac,3195887,"Arterial occlusion, mesenteric arterial system...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Chest-abdomen,NaN
3201,Vascular,3195887,"Arterial occlusion, mesenteric arterial system...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Chest-abdomen,NaN
185,Cardiac,3195888,"Arterial occlusion, renal arterial system, emb...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Chest-abdomen,NaN
3202,Vascular,3195888,"Arterial occlusion, renal arterial system, emb...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Chest-abdomen,NaN
186,Cardiac,3195889,"Arterial occlusion, renal infarcts, embolic et...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Chest-abdomen,NaN
3203,Vascular,3195889,"Arterial occlusion, renal infarcts, embolic et...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Chest-abdomen,NaN
187,Cardiac,3195885,"Arterial occlusion, upper extremity, embolic e...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Chest-abdomen,NaN
3204,Vascular,3195885,"Arterial occlusion, upper extremity, embolic e...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Chest-abdomen,NaN
3247,Vascular,3106361,"HTN, high suspicion renal vascular, decreased ...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3074,Urologic,3106361,"HTN, high suspicion renal vascular, decreased ...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3075,Urologic,3073720,"HTN, high suspicion renal vascular, normal ren...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3248,Vascular,3073720,"HTN, high suspicion renal vascular, normal ren...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3263,Vascular,3141499,"Mesenteric ischemia, acute, suspected, initial...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen-pelvis,NaN
329,Gastrointestinal,3141499,"Mesenteric ischemia, acute, suspected, initial...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen-pelvis,NaN
3264,Vascular,3141500,"Mesenteric ischemia, chronic, suspected, initi...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen-pelvis,NaN
330,Gastrointestinal,3141500,"Mesenteric ischemia, chronic, suspected, initi...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen-pelvis,NaN
2985,Thoracic,3196674,"Sepsis suspected, acute abdominal pain, initia...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3131,Urologic,3196674,"Sepsis suspected, acute abdominal pain, initia...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
368,Gastrointestinal,3196674,"Sepsis suspected, acute abdominal pain, initia...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3003,Thoracic,3196675,"Sepsis, acute abdominal pain, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3149,Urologic,3196675,"Sepsis, acute abdominal pain, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
386,Gastrointestinal,3196675,"Sepsis, acute abdominal pain, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3305,Vascular,3102193,"Upper GI bleeding suspected, nonvariceal, no e...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
409,Gastrointestinal,3102193,"Upper GI bleeding suspected, nonvariceal, no e...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3306,Vascular,3197481,"Upper GI bleeding, nonvariceal, clear source o...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
410,Gastrointestinal,3197481,"Upper GI bleeding, nonvariceal, clear source o...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3307,Vascular,3102194,"Upper GI bleeding, nonvariceal, clear source o...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
411,Gastrointestinal,3102194,"Upper GI bleeding, nonvariceal, clear source o...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
412,Gastrointestinal,3102196,"Upper GI bleeding, nonvariceal, endoscopy nega...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3308,Vascular,3102196,"Upper GI bleeding, nonvariceal, endoscopy nega...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
413,Gastrointestinal,3102195,"Upper GI bleeding, nonvariceal, no clear sourc...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3309,Vascular,3102195,"Upper GI bleeding, nonvariceal, no clear sourc...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
414,Gastrointestinal,3197482,"Upper GI bleeding, nonvariceal, postsurgical c...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3310,Vascular,3197482,"Upper GI bleeding, nonvariceal, postsurgical c...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
415,Gastrointestinal,3197483,"Upper GI bleeding, nonvariceal, traumatic caus...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN
3311,Vascular,3197483,"Upper GI bleeding, nonvariceal, traumatic caus...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen,NaN

In [91]:
studies = pd.read_csv('data/combined.csv')
studies.head()

,Unnamed: 0,panel,scenario-text,scenario-id,procedure,adult-rrl,peds-rrl,appropriateness
0,0,Pediatric,Acquired coronary artery abnormality suspected...,3196446,MRA chest without and with IV contrast,0 mSvO,0 mSv [ped]O,Usually appropriate
1,0,Pediatric,Acquired coronary artery abnormality suspected...,3196446,MRA chest without and with IV contrast,0 mSvO,0 mSv [ped]O,Usually appropriate
2,1,Pediatric,Acquired coronary artery abnormality suspected...,3196446,MRA chest without IV contrast,0 mSvO,0 mSv [ped]O,Usually appropriate
3,2,Pediatric,Acquired coronary artery abnormality suspected...,3196446,MRI heart function and morphology without and ...,0 mSvO,0 mSv [ped]O,Usually appropriate
4,3,Pediatric,Acquired coronary artery abnormality suspected...,3196446,MRI heart function and morphology without IV c...,0 mSvO,0 mSv [ped]O,Usually appropriate

In [92]:
studies['procedure'].unique()

array(['MRA chest without and with IV contrast',
       'MRA chest without IV contrast',
       'MRI heart function and morphology without and with IV contrast',
       ..., 'US duplex Doppler groin',
       'US-guided fine needle aspiration biopsy groin',
       'Lymphoscintigraphy groin'], dtype=object)

In [93]:
studies['appropriateness'].unique()

array(['Usually appropriate', 'May be appropriate',
       'May be appropriate (Disagreement)', 'Usually not appropriate'],
      dtype=object)

In [94]:
for scenario_text in duplicate_scenarios['scenario-text'].unique():
    scenario_rows = duplicate_scenarios[duplicate_scenarios['scenario-text'] == scenario_text]
    for index, row in scenario_rows.iterrows():
        scenario_id = row['scenario-id']
        studies_for_scenario = studies[studies['scenario-id'] == scenario_id]['procedure'].tolist()
        studies_for_scenario = set(studies_for_scenario)
        
        if index == scenario_rows.index[0]:
            first_studies_set = studies_for_scenario
            has_different_studies = False
        else:
            if studies_for_scenario != first_studies_set:
                has_different_studies = True
                print("Discrepancy found for scenario-id:", scenario_id)

In [95]:

filtered_df = filtered_df.drop_duplicates(subset=['scenario-text'], keep='first')
without_duplicates_n = len(filtered_df)
without_duplicates_n

186

In [96]:

import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Funnel(
    name = 'ACR Criteria',
    y = ['All Scenarios', 'Limit by Body Area', 'Without Pediatrics', 'Without Pregnant', 'Without IR', 'Without Monitoring<br>("Staging", "Screen", "Surveillance")', 'Without Pelvis Only', 'Without Duplicate Scenarios'],
    x = [len(df), body_area_n, without_peds_n, without_pregnant_n, without_IR_n, without_monitoring_n, without_pelvis_n, without_duplicates_n],
    textinfo = "value+percent initial"
))

fig.update_layout(
    title = "ACR Criteria Funnel Analysis",
    showlegend = True,
    width = 800,
    height = 500
)

fig.show()

In [97]:
removed_df = df[~df.index.isin(filtered_df.index)]
len(removed_df)

3160

In [98]:

with pd.ExcelWriter('category_analysis.xlsx') as writer:
    filtered_df.to_excel(writer, sheet_name='Filtered Rows', index=False)
    removed_df.to_excel(writer, sheet_name='All Removed Rows', index=False)
    removed_pelvis_df.to_excel(writer, sheet_name='Removed Pelvis Rows', index=False)

In [99]:
filtered_df.head()

,panel,scenario-id,scenario-text,scenario-url,sex,age,body-area,priority-clinical-areas
184,Cardiac,3195887,"Arterial occlusion, mesenteric arterial system...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Chest-abdomen,NaN
185,Cardiac,3195888,"Arterial occlusion, renal arterial system, emb...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Chest-abdomen,NaN
186,Cardiac,3195889,"Arterial occlusion, renal infarcts, embolic et...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Chest-abdomen,NaN
187,Cardiac,3195885,"Arterial occlusion, upper extremity, embolic e...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Chest-abdomen,NaN
246,Gastrointestinal,3081311,"Abd pain, acute, nonlocalized, fever, initial ...",https://gravitas.acr.org/ACPortal/GetDataForOn...,All,18 - 150,Abdomen-pelvis,NaN

Questions to answer, for each scenario, does the ACR recommend?
- No imaging (all studies are rated as “usually not appropriate”)
- CT is the ONLY “usually appropriate” imaging
- CT and other modalities are “usually appropriate” imaging (“alternatives to CT possible”)
- CT not “usually appropriate”
    - CT is “may be appropriate”
    - CT “usually not appropriate”

In [100]:

for index, scenario in filtered_df.iterrows():
    # Get all studies for this scenario
    scenario_studies = studies[studies['scenario-id'] == scenario['scenario-id']]
    
    # Check if any CT procedures are usually appropriate
    ct_studies = scenario_studies[
        (scenario_studies['procedure'].str.startswith('CT', na=False)) & 
        (scenario_studies['appropriateness'] == 'Usually appropriate')
    ]
    filtered_df.at[index, 'ct_usually_appropriate'] = len(ct_studies) > 0
    
    # Check if any CT procedures are may be appropriate
    ct_studies = scenario_studies[
        (scenario_studies['procedure'].str.startswith('CT', na=False)) & 
        (scenario_studies['appropriateness'] == 'May be appropriate')
    ]
    filtered_df.at[index, 'ct_may_be_appropriate'] = len(ct_studies) > 0

    # Check if any CT procedures are NOT appropriate
    ct_inappropriate_studies = scenario_studies[
        (scenario_studies['procedure'].str.startswith('CT', na=False)) & 
        (scenario_studies['appropriateness'] == 'Usually not appropriate')
    ]
    filtered_df.at[index, 'ct_not_appropriate'] = len(ct_inappropriate_studies) > 0
    
    # Are non CT studies usually appropriate?
    non_ct_studies = scenario_studies[
        (~scenario_studies['procedure'].str.startswith('CT', na=False)) & 
        (scenario_studies['appropriateness'] == 'Usually appropriate')
    ]
    filtered_df.at[index, 'other_usually_appropriate'] = len(non_ct_studies) > 0

    # Are non CT studies maybe appropriate?
    non_ct_studies = scenario_studies[
        (~scenario_studies['procedure'].str.startswith('CT', na=False)) & 
        (scenario_studies['appropriateness'] == 'May be appropriate')
    ]
    filtered_df.at[index, 'other_may_be_appropriate'] = len(non_ct_studies) > 0

    # Are non CT studies NOT appropriate?
    non_ct_studies = scenario_studies[
        (~scenario_studies['procedure'].str.startswith('CT', na=False)) & 
        (scenario_studies['appropriateness'] == 'Usually not appropriate')
    ]
    filtered_df.at[index, 'other_not_appropriate'] = len(non_ct_studies) > 0

In [101]:

filtered_df[['ct_usually_appropriate', 'other_usually_appropriate', 'ct_may_be_appropriate', 'other_may_be_appropriate', 'ct_not_appropriate', 'other_not_appropriate']].describe()

,ct_usually_appropriate,other_usually_appropriate,ct_may_be_appropriate,other_may_be_appropriate,ct_not_appropriate,other_not_appropriate
count,186,186,186,186,186,186
unique,2,2,2,2,2,2
top,True,True,True,True,True,True
freq,139,138,135,146,156,169

In [102]:
percentage_usually_appropriate = (filtered_df['ct_usually_appropriate'].sum() / len(filtered_df)) * 100
print(f"Percentage of scenarios where a CT study is usually appropriate: {percentage_usually_appropriate:.2f}%")

Percentage of scenarios where a CT study is usually appropriate: 74.73%

In [103]:

percentage_neither = len(filtered_df[(filtered_df['ct_usually_appropriate'] == False) & (filtered_df['ct_may_be_appropriate'] == False)]) / len(filtered_df) * 100
print(f"Percentage of scenarios where a CT study is neither 'usually appropriate' nor 'may be appropriate': {percentage_neither:.2f}%")

Percentage of scenarios where a CT study is neither 'usually appropriate' nor 'may be appropriate': 6.45%

In [109]:
filtered_df[(filtered_df['ct_usually_appropriate'] == False) & (filtered_df['ct_may_be_appropriate'] == False)]['scenario-text']

295     Epigastric pain, hiatal hernia suspected, init...
1425    Soft tissue infection suspected, abdomen, init...
1557    Soft tissue mass, abdomen, superficial, initia...
3041    Adrenal mass, >=4cm on imaging, no benign feat...
3042    Adrenal mass, indeterminate, <1cm on imaging, ...
3043    Adrenal mass, indeterminate, >=4cm on imaging,...
3083    Prostate cancer suspected, no prior biopsy, in...
3084    Prostate cancer suspected, TRUS guided biopsy ...
3106    Pyelonephritis suspected, acute, uncomplicated...
3122                         Renal transplant dysfunction
3184    UTI, lower urinary tract, recurrent, uncomplic...
3250    Iliocaval disease, severe post thrombotic chan...
Name: scenario-text, dtype: object

In [105]:

appropriate_percentage = (
    (filtered_df['ct_usually_appropriate'] | filtered_df['ct_may_be_appropriate']).mean() * 100
)
print(f"Percentage of cases where CT is usually or may be appropriate: {appropriate_percentage:.2f}%")

Percentage of cases where CT is usually or may be appropriate: 93.55%

In [106]:
filtered_df[filtered_df['ct_usually_appropriate'] == False]['scenario-text']

258     Abnormal liver function tests, hepatocellular ...
290     Epigastric pain, acid reflux suspected, initia...
291     Epigastric pain, duodenal ulcer suspected, ini...
292     Epigastric pain, esophagitis suspected, initia...
294     Epigastric pain, gastritis suspected, initial ...
295     Epigastric pain, hiatal hernia suspected, init...
296     Epigastric pain, peptic ulcer suspected, initi...
316     Liver lesion, <1cm, indeterminate on US, hx of...
331     Pancreas cyst, <=2.5cm, incidental, initial ev...
332     Pancreas cyst, >2.5cm, incidental, high risk f...
333     Pancreas cyst, >2.5cm, incidental, no high ris...
335     Pancreas duct dilation, >7mm, IPMN suspected, ...
340          Pancreatitis suspected, typical presentation
357     RUQ pain, acalculous cholecystitis suspected, ...
358     RUQ pain, acalculous cholecystitis suspected, ...
359     RUQ pain, biliary disease suspected, initial i...
1425    Soft tissue infection suspected, abdomen, init...
1554    Soft tissue mass, abdomen, nonsuperficial, ini...
1556    Soft tissue mass, abdomen, radiography and non...
1557    Soft tissue mass, abdomen, superficial, initia...
3041    Adrenal mass, >=4cm on imaging, no benign feat...
3042    Adrenal mass, indeterminate, <1cm on imaging, ...
3043    Adrenal mass, indeterminate, >=4cm on imaging,...
3055    Flank pain, acute, stone disease suspected, CT...
3064    Hematuria, current or recent menses, initial i...
3066    Hematuria, microscopic, infection or viral ill...
3067    Hematuria, microscopic, no risk factors, initi...
3069    Hematuria, microscopic, recent vigorous exerci...
3074    HTN, high suspicion renal vascular, decreased ...
3077    Hydronephrosis, unknown cause, bilateral, asym...
3078    Hydronephrosis, unknown cause, solitary kidney...
3083    Prostate cancer suspected, no prior biopsy, in...
3084    Prostate cancer suspected, TRUS guided biopsy ...
3092    Prostate cancer, recurrent disease suspected, ...
3093    Prostate cancer, recurrent disease suspected, ...
3094    Prostate cancer, residual disease suspected, p...
3095    Prostate cancer, residual disease suspected, p...
3106    Pyelonephritis suspected, acute, uncomplicated...
3115    Renal failure, acute kidney injury, initial im...
3116    Renal failure, chronic kidney disease, initial...
3117    Renal failure, kidney disease unknown duration...
3118    Renal failure, neurogenic bladder, initial ima...
3119    Renal mass, indeterminate, contraindication to...
3120    Renal mass, indeterminate, contraindication to...
3122                         Renal transplant dysfunction
3184    UTI, lower urinary tract, recurrent, uncomplic...
3250    Iliocaval disease, severe post thrombotic chan...
Name: scenario-text, dtype: object

In [112]:

filtered_df[(filtered_df['ct_usually_appropriate'] == False) & 
           (filtered_df['ct_may_be_appropriate'] == False) & 
           (filtered_df['other_usually_appropriate'] == False) & 
           (filtered_df['other_may_be_appropriate'] == False)]['scenario-text']

3042    Adrenal mass, indeterminate, <1cm on imaging, ...
3043    Adrenal mass, indeterminate, >=4cm on imaging,...
3106    Pyelonephritis suspected, acute, uncomplicated...
3184    UTI, lower urinary tract, recurrent, uncomplic...
Name: scenario-text, dtype: object