In [1]:

import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
df = pd.read_csv('acr_ac_scenarios.csv')
df.head()

,panel,scenario-id,scenario-text,scenario-url,sex,age,body-area,priority-clinical-areas
0,Breast,3110141,"Axillary adenopathy, breast cancer suspected",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=3209,Male Only,18 - 150,Breast,NaN
1,Breast,3194817,"Axillary lump, palpable, new, bilateral, initial axilla imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5930,Female Only,18 - 150,Breast,NaN
2,Breast,3194815,"Axillary lump, palpable, new, unilateral, initial axilla imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5929,Female Only,18 - 150,Breast,NaN
3,Breast,3194837,"Axillary node, suspicious on imaging, not mammo or US, next imaging study",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5940,Female Only,18 - 150,Breast,NaN
4,Breast,3194835,"Axillary node, suspicious on mammo or US, next imaging study",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5939,Female Only,18 - 150,Breast,NaN

In [2]:
len(df)

3346

In [3]:
df['age'].unique()

<StringArray>
[   '18 - 150',    '25 - 150',    '30 - 150',    '40 - 150',     '12 - 29',
     '30 - 39',     '10 - 60',     '40 - 60',     '18 - 29',      '0 - 24',
      '0 - 29',      '0 - 17',     '0 - 150',    '45 - 150',    '12 - 150',
     '5 - 150',    '16 - 150',     '18 - 49',     '6 - 150',    '10 - 150',
       '0 - 9',    '65 - 150',     '16 - 64',    '50 - 150',    '70 - 150',
    '80 - 150',    '51 - 150',       '0 - 7',       '0 - 8',    '66 - 150',
      '0 - 15',  'D90 - 6205',    'D0 - 729',       '45339',       '0 - 1',
    'D0 - 119', 'D181 - 6205',  'D120 - 180',     'D0 - 27',   'D28 - 119',
    'D0 - 179',     'D0 - 29',       '45366',       '0 - 3',       '0 - 4',
       '45429', 'D180 - 6205',       '0 - 5',     'D0 - 30',  'D31 - 6205',
       '45582',  'D30 - 1095',       '45368',       '0 - 2', 'D180 - 1825',
  'D30 - 6205',     'D0 - 28',     'D0 - 59',  'D60 - 2190',       '45490',
      'D0 - 2',    'D3 - 365',    'D15 - 90',     '50 - 80',    '35 - 150',
     '18 - 39',      '18-150']
Length: 67, dtype: str

In [4]:
df['body-area'].unique()

<StringArray>
[              'Breast',        'Cardiac-chest', 'Chest-abdomen-pelvis',
        'Chest-abdomen',              'Cardiac',                'Chest',
 'cardiac-chest-pelvis',       'Abdomen-pelvis',              'Abdomen',
               'Pelvis',           'Neck-chest',          'Unspecified',
          'Extremities',                'Spine',      'Lower extremity',
      'Upper extremity',         'Spine-pelvis',                 'Head',
                 'Neck',            'Head-neck',              'Maxface',
           'Head-spine']
Length: 22, dtype: str

In [5]:

filtered_df = df[df['body-area'].isin(['Chest-abdomen', 'Chest-abdomen-pelvis', 'Abdomen-pelvis', 'Abdomen', 'Pelvis'])]
body_area_n = len(filtered_df)
print(body_area_n)

620

In [6]:
filtered_df = filtered_df[filtered_df['panel'] != 'Pediatric']
without_peds_n = len(filtered_df)
print(without_peds_n)

562

In [7]:

filtered_df = filtered_df[~filtered_df['scenario-text'].str.contains('pregnant', case=False, na=False)]
without_pregnant_n = len(filtered_df)
print(without_pregnant_n)

547

In [8]:
filtered_df = filtered_df[filtered_df['panel'] != 'Interventional Radiology']
without_IR_n = len(filtered_df)
print(without_IR_n)

509

In [9]:
pattern_list = ['staging', 
                'screen', 
                'surveillance',
                'incidental finding',
                'imaging during treatment',
                'posttreatment imaging',
                'post treatment imaging',
                'preop planning',
                'pre-op planning'
                ]

pattern = '|'.join(pattern_list)
filtered_df = filtered_df[~filtered_df['scenario-text'].str.contains(pattern, case=False, na=False)]
without_monitoring_n = len(filtered_df)
print(without_monitoring_n)

398

In [10]:
# removed_pelvis_df = filtered_df[filtered_df['body-area'] == 'Pelvis']
# filtered_df = filtered_df[filtered_df['body-area'] != 'Pelvis']
# without_pelvis_n = len(filtered_df)
# print(without_pelvis_n)

In [11]:
# temporary to pull out pelvis scenarios for secondary review
pelvis_df = filtered_df[filtered_df['body-area'] == 'Pelvis']
display(pelvis_df)

,panel,scenario-id,scenario-text,scenario-url,sex,age,body-area,priority-clinical-areas
278,Gastrointestinal,3195285,"Deep pelvic hernia suspected, obturator, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=6237,All,18 - 150,Pelvis,NaN
279,Gastrointestinal,3195287,"Deep pelvic hernia suspected, perineal, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=6239,All,18 - 150,Pelvis,NaN
280,Gastrointestinal,3195286,"Deep pelvic hernia suspected, sciatic, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=6238,All,18 - 150,Pelvis,NaN
344,Gastrointestinal,3194184,"Perianal abscess suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5555,All,18 - 150,Pelvis,NaN
345,Gastrointestinal,3194185,"Perianal fistula suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5556,All,18 - 150,Pelvis,NaN
352,Gastrointestinal,3194188,"Rectovaginal fistula suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5558,All,18 - 150,Pelvis,NaN
353,Gastrointestinal,3194187,"Rectovesicular fistula suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5557,All,18 - 150,Pelvis,NaN
416,Gyn and OB,3197148,"Adnexal mass suspected, no acute symptoms, postmenopausal, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7520,Female Only,18 - 150,Pelvis,NaN
418,Gyn and OB,3074166,"Adnexal mass suspected, no acute symptoms, premenopausal, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=877,Female Only,18 - 150,Pelvis,NaN
419,Gyn and OB,3082200,"Adnexal mass, likely benign, no acute symptoms, postmenopausal, follow-up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=1171,Female Only,18 - 150,Pelvis,NaN
420,Gyn and OB,3074171,"Adnexal mass, likely benign, no acute symptoms, premenopausal, follow-up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=881,Female Only,18 - 150,Pelvis,NaN
421,Gyn and OB,3149341,"Adnexal mass, no acute symptoms, postmenopausal, initial pelvic US indeterminate, follow-up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=4705,Female Only,18 - 150,Pelvis,NaN
422,Gyn and OB,3197151,"Adnexal mass, no acute symptoms, postmenopausal, initial pelvic US indeterminate, next imaging study for characterization",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7522,Female Only,18 - 150,Pelvis,NaN
423,Gyn and OB,3197155,"Adnexal mass, no acute symptoms, postmenopausal, pelvic US suspicious for malignancy, next imaging study for characterization",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7523,Female Only,18 - 150,Pelvis,NaN
425,Gyn and OB,3082202,"Adnexal mass, no acute symptoms, premenopausal, initial pelvic US indeterminate, follow-up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=1172,Female Only,18 - 150,Pelvis,NaN
426,Gyn and OB,3197150,"Adnexal mass, no acute symptoms, premenopausal, initial pelvic US indeterminate, next imaging study for characterization",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7521,Female Only,18 - 150,Pelvis,NaN
427,Gyn and OB,3149342,"Adnexal mass, no acute symptoms, premenopausal, pelvic US suspicious for malignancy, next imaging study for characterization",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=4706,Female Only,18 - 150,Pelvis,NaN
428,Gyn and OB,3196732,"Cervical cancer, chemoradiation, posttreatment evaluation",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7287,Female Only,18 - 150,Pelvis,NaN
429,Gyn and OB,3196735,"Cervical cancer, local recurrence suspected, follow-up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7288,Female Only,18 - 150,Pelvis,NaN
430,Gyn and OB,3196736,"Cervical cancer, local recurrence, follow-up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7289,Female Only,18 - 150,Pelvis,NaN
431,Gyn and OB,3196737,"Cervical cancer, mets recurrence suspected, follow-up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7290,Female Only,18 - 150,Pelvis,NaN
432,Gyn and OB,3196738,"Cervical cancer, mets recurrence, follow-up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7291,Female Only,18 - 150,Pelvis,NaN
436,Gyn and OB,3194854,"Defecatory dysfunction, difficulty initiating defecation, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5955,Female Only,18 - 150,Pelvis,NaN
437,Gyn and OB,3194857,"Defecatory dysfunction, digital maneuvers to defecate, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5958,Female Only,18 - 150,Pelvis,NaN
438,Gyn and OB,3194855,"Defecatory dysfunction, incomplete evacuation, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5956,Female Only,18 - 150,Pelvis,NaN
439,Gyn and OB,3194852,"Defecatory dysfunction, incontinence of gas, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5953,Female Only,18 - 150,Pelvis,NaN
440,Gyn and OB,3194851,"Defecatory dysfunction, incontinence of liquid, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5952,Female Only,18 - 150,Pelvis,NaN
441,Gyn and OB,3194850,"Defecatory dysfunction, incontinence of stool, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5951,Female Only,18 - 150,Pelvis,NaN
442,Gyn and OB,3194856,"Defecatory dysfunction, splinting, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5957,Female Only,18 - 150,Pelvis,NaN
443,Gyn and OB,3194853,"Defecatory dysfunction, straining during defecation, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5954,Female Only,18 - 150,Pelvis,NaN
444,Gyn and OB,3185436,"Endometrial cancer, pretreatment evaluation, low grade, assess lymph node and mets",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5387,Female Only,18 - 150,Pelvis,NaN
449,Gyn and OB,3079768,"Endometrial cancer, treated, recurrence suspected",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=1100,Female Only,18 - 150,Pelvis,NaN
450,Gyn and OB,3197524,"Endometriosis suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7774,Female Only,18 - 150,Pelvis,NaN
451,Gyn and OB,3197531,"Endometriosis suspected, rectosigmoid, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7779,Female Only,18 - 150,Pelvis,NaN
452,Gyn and OB,3197526,"Endometriosis suspected, US indeterminate, next imaging study, characterization",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7775,Female Only,18 - 150,Pelvis,NaN
453,Gyn and OB,3197527,"Endometriosis suspected, US indeterminate, next imaging study, treatment planning",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7776,Female Only,18 - 150,Pelvis,NaN
454,Gyn and OB,3197528,"Endometriosis suspected, US negative, next imaging study, characterization",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7777,Female Only,18 - 150,Pelvis,NaN
455,Gyn and OB,3197529,"Endometriosis suspected, US negative, next imaging study, treatment planning",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7778,Female Only,18 - 150,Pelvis,NaN
456,Gyn and OB,3197534,"Endometriosis, postoperative diagnosis, new symptoms, follow-up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7781,Female Only,18 - 150,Pelvis,NaN
457,Gyn and OB,3197533,"Endometriosis, postoperative diagnosis, ongoing symptoms, follow-up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7780,Female Only,18 - 150,Pelvis,NaN
462,Gyn and OB,3149273,"Fetal growth disturbance, high risk for fetal growth restriction",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=4637,Female Only,10 - 60,Pelvis,NaN
463,Gyn and OB,3149272,"Fetal growth disturbance, low risk for fetal growth restriction",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=4636,Female Only,10 - 60,Pelvis,NaN
464,Gyn and OB,3149274,"Fetal growth restriction, follow up",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=4638,Female Only,10 - 60,Pelvis,NaN
465,Gyn and OB,3195269,"Fibroids suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=6226,Female Only,18 - 150,Pelvis,NaN
468,Gyn and OB,3195271,"Fibroids, treatment planning, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=6227,Female Only,18 - 150,Pelvis,NaN
469,Gyn and OB,3155923,Gestational trophoblastic disease (GTD) suspected,https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=4786,Female Only,10 - 60,Pelvis,NaN
470,Gyn and OB,3163053,"Gestational trophoblastic disease (GTD), assess for complications",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=4912,Female Only,10 - 60,Pelvis,NaN
471,Gyn and OB,3163051,Gestational trophoblastic neoplasia (GTN) suspected,https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=4910,Female Only,10 - 60,Pelvis,NaN
472,Gyn and OB,3163054,"Gestational trophoblastic neoplasia (GTN), assess for complications",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=4913,Female Only,10 - 60,Pelvis,NaN
475,Gyn and OB,3183774,"Gravid cervix assessment, active term labor, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5337,Female Only,10 - 60,Pelvis,NaN
476,Gyn and OB,3181230,"Gravid cervix assessment, hx of preterm birth, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5302,Female Only,10 - 60,Pelvis,NaN
477,Gyn and OB,3183773,"Gravid cervix assessment, labor induction, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5336,Female Only,10 - 60,Pelvis,NaN
478,Gyn and OB,3183772,"Gravid cervix assessment, no hx of preterm birth, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5335,Female Only,10 - 60,Pelvis,NaN
479,Gyn and OB,3183771,"Gravid cervix assessment, nulliparous, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5334,Female Only,10 - 60,Pelvis,NaN
480,Gyn and OB,3181231,"Gravid cervix assessment, preterm labor suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5303,Female Only,10 - 60,Pelvis,NaN
481,Gyn and OB,3180663,"Infertility, endometriosis suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5291,Female Only,10 - 60,Pelvis,NaN
482,Gyn and OB,3180664,"Infertility, endometriosis, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5292,Female Only,10 - 60,Pelvis,NaN
483,Gyn and OB,3164925,"Infertility, evaluate ovulatory function and reserve, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5239,Female Only,10 - 60,Pelvis,NaN
484,Gyn and OB,3180661,"Infertility, polycystic ovary syndrome suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5289,Female Only,10 - 60,Pelvis,NaN
485,Gyn and OB,3180662,"Infertility, polycystic ovary syndrome, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5290,Female Only,10 - 60,Pelvis,NaN
486,Gyn and OB,3097329,"Infertility, recurring pregnancy loss, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=2123,Female Only,10 - 60,Pelvis,NaN
487,Gyn and OB,3164926,"Infertility, tubal occlusion suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5240,Female Only,10 - 60,Pelvis,NaN
488,Gyn and OB,3197485,"Multiple gestations suspected, dichorionic, first trimester, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7756,Female Only,10 - 60,Pelvis,NaN
489,Gyn and OB,3197486,"Multiple gestations suspected, monochorionic, first trimester, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7757,Female Only,10 - 60,Pelvis,NaN
491,Gyn and OB,3197494,"Multiple gestations, dichorionic twins, second trimester anatomy exam, follow-up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7763,Female Only,10 - 60,Pelvis,NaN
494,Gyn and OB,3197490,"Multiple gestations, dichorionic, first trimester US performed, next imaging study",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7760,Female Only,10 - 60,Pelvis,NaN
495,Gyn and OB,3197487,"Multiple gestations, dichorionic, first trimester, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7758,Female Only,10 - 60,Pelvis,NaN
497,Gyn and OB,3197496,"Multiple gestations, monochorionic twins, second trimester anatomy exam, follow-up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7764,Female Only,10 - 60,Pelvis,NaN
500,Gyn and OB,3197491,"Multiple gestations, monochorionic, first trimester US performed, next imaging study",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7761,Female Only,10 - 60,Pelvis,NaN
501,Gyn and OB,3197488,"Multiple gestations, monochorionic, first trimester, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7759,Female Only,10 - 60,Pelvis,NaN
505,Gyn and OB,3197493,"Multiple gestations, multichorionic higher order multiples, second trimester anatomy exam, follow-up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=7762,Female Only,10 - 60,Pelvis,NaN
506,Gyn and OB,3185425,"Nuchal translucency measurement, increased, 11-14 weeks gestation, dichorionic twins",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5376,Female Only,10 - 60,Pelvis,NaN
507,Gyn and OB,3185426,"Nuchal translucency measurement, increased, 11-14 weeks gestation, monochorionic twins,",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5377,Female Only,10 - 60,Pelvis,NaN
508,Gyn and OB,3185424,"Nuchal translucency measurement, increased, 11-14 weeks gestation, single gestation",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5375,Female Only,10 - 60,Pelvis,NaN
509,Gyn and OB,3185423,"Nuchal translucency measurement, routine, 11-14 weeks gestation, single or twins, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5374,Female Only,10 - 60,Pelvis,NaN
515,Gyn and OB,3141652,"Ovarian cancer, recurrence known",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=4450,Female Only,18 - 150,Pelvis,NaN
516,Gyn and OB,3141651,"Ovarian cancer, recurrence suspected",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=4449,Female Only,18 - 150,Pelvis,NaN
517,Gyn and OB,3194860,"Pelvic floor surgery, postoperative, chronic complications, not recurrent pelvic floor dysfunction, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5960,Female Only,18 - 150,Pelvis,NaN
518,Gyn and OB,3194859,"Pelvic floor surgery, postoperative, subacute complications, not recurrent pelvic floor dysfunction, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5959,Female Only,18 - 150,Pelvis,NaN
519,Gyn and OB,3194841,"Pelvic organ prolapse suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5943,Female Only,18 - 150,Pelvis,NaN
520,Gyn and OB,3074377,"Pelvic pain, acute, negative beta-hCG, gynecological etiology suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=1042,Female Only,10 - 60,Pelvis,NaN
521,Gyn and OB,3074379,"Pelvic pain, acute, negative beta-hCG, non-gynecological etiology suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=1044,Female Only,10 - 60,Pelvis,NaN
522,Gyn and OB,3074376,"Pelvic pain, acute, positive beta-hCG, gynecological etiology suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=1041,Female Only,10 - 60,Pelvis,NaN
523,Gyn and OB,3074378,"Pelvic pain, acute, positive beta-hCG, non-gynecological etiology suspected, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=1043,Female Only,10 - 60,Pelvis,NaN
524,Gyn and OB,3193989,"Pelvic pain, acute, postmenopausal, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5482,Female Only,18 - 150,Pelvis,NaN
525,Gyn and OB,3148178,"Pelvic pain, chronic, post-menopausal",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=4553,Female Only,18 - 150,Pelvis,NaN
526,Gyn and OB,3148585,"Perineal pain, chronic, post-menopausal",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=4573,Female Only,18 - 150,Pelvis,NaN
528,Gyn and OB,3164899,"Placenta accreta spectrum disorder suspected, high risk, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5213,Female Only,10 - 60,Pelvis,NaN
529,Gyn and OB,3164900,"Placenta accreta spectrum disorder, follow up imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5214,Female Only,10 - 60,Pelvis,NaN
530,Gyn and OB,3185407,"Postpartum hemorrhage, <= 24 hrs after cesarean delivery, initial Imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5358,Female Only,10 - 60,Pelvis,NaN
531,Gyn and OB,3185408,"Postpartum hemorrhage, <= 24 hrs after vaginal delivery, initial Imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5359,Female Only,10 - 60,Pelvis,NaN
532,Gyn and OB,3185409,"Postpartum hemorrhage, >24hrs to <= 6wks hrs after cesarean delivery, initial Imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5360,Female Only,10 - 60,Pelvis,NaN
533,Gyn and OB,3185410,"Postpartum hemorrhage, >24hrs to <= 6wks hrs after vaginal delivery, initial Imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5361,Female Only,10 - 60,Pelvis,NaN
534,Gyn and OB,3194848,"Urinary dysfunction, digital maneuvers to void, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5950,Female Only,18 - 150,Pelvis,NaN
535,Gyn and OB,3194843,"Urinary dysfunction, frequent urination, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5945,Female Only,18 - 150,Pelvis,NaN
536,Gyn and OB,3194846,"Urinary dysfunction, incomplete voiding, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5948,Female Only,18 - 150,Pelvis,NaN
537,Gyn and OB,3194842,"Urinary dysfunction, involuntary leakage of urine, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5944,Female Only,18 - 150,Pelvis,NaN
538,Gyn and OB,3194847,"Urinary dysfunction, splinting, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5949,Female Only,18 - 150,Pelvis,NaN
539,Gyn and OB,3194845,"Urinary dysfunction, straining to void, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5947,Female Only,18 - 150,Pelvis,NaN
540,Gyn and OB,3194844,"Urinary dysfunction, urgency, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5946,Female Only,18 - 150,Pelvis,NaN
541,Gyn and OB,3185427,"Uterine bleeding, abnormal, initial imaging",https://gravitas.acr.org/ACPortal/GetDataForOneScenario?senarioId=5378,Female Only,12 - 150,Pelvis,NaN

In [ ]:
specific_scenarios_to_include = pd.read_csv('include.csv')
specific_scenarios_to_exclude = pd.read_csv('exclude.csv')

In [ ]:
included_scenarios = specific_scenarios_to_include.merge(
    df[['scenario-id', 'scenario-text']].drop_duplicates(),
    on='scenario-id',
    how='left'
).drop_duplicates().sort_values('scenario-id')

excluded_scenarios = specific_scenarios_to_exclude.merge(
    df[['scenario-id', 'scenario-text']].drop_duplicates(),
    on='scenario-id',
    how='left'
).drop_duplicates().sort_values('scenario-id')

print("Included scenarios:")
display(included_scenarios)

print("\nExcluded scenarios:")
display(excluded_scenarios)

In [ ]:
df[df['scenario-id'].isin(included_scenarios['scenario-id'])].sort_values('scenario-id')

In [ ]:

filtered_df = pd.concat([filtered_df, df[df['scenario-id'].isin(specific_scenarios_to_include['scenario-id'])]])
print(len(filtered_df))

In [ ]:
exclude_ids = set(specific_scenarios_to_exclude['scenario-id'])
filtered_ids = set(filtered_df['scenario-id'])

missing_in_filtered = exclude_ids - filtered_ids

missing_scenarios = df[df['scenario-id'].isin(missing_in_filtered)].sort_values('scenario-id')

print(f"Excluded scenario IDs not present in filtered_df: {len(missing_scenarios)}")
display(missing_scenarios)

In [ ]:
excluded_in_filtered = filtered_df[filtered_df['scenario-id'].isin(specific_scenarios_to_exclude['scenario-id'])]
display(excluded_in_filtered)

In [ ]:
filtered_df = filtered_df[~filtered_df['scenario-id'].isin(specific_scenarios_to_exclude['scenario-id'])]
print(len(filtered_df))

In [ ]:

# Find duplicate scenario texts
duplicate_scenarios = filtered_df[filtered_df.duplicated(subset=['scenario-text'], keep=False)]
duplicate_scenarios = duplicate_scenarios.sort_values('scenario-text')
print(f"Found {len(duplicate_scenarios)} rows with duplicate scenarios")
display(duplicate_scenarios)

In [ ]:
studies = pd.read_csv('data/combined.csv')
studies.head()

In [ ]:
studies['procedure'].unique()

In [ ]:
studies['appropriateness'].unique()

In [ ]:
for scenario_text in duplicate_scenarios['scenario-text'].unique():
    scenario_rows = duplicate_scenarios[duplicate_scenarios['scenario-text'] == scenario_text]
    for index, row in scenario_rows.iterrows():
        scenario_id = row['scenario-id']
        studies_for_scenario = studies[studies['scenario-id'] == scenario_id]['procedure'].tolist()
        studies_for_scenario = set(studies_for_scenario)
        
        if index == scenario_rows.index[0]:
            first_studies_set = studies_for_scenario
            has_different_studies = False
        else:
            if studies_for_scenario != first_studies_set:
                has_different_studies = True
                print("Discrepancy found for scenario-id:", scenario_id)

In [ ]:

filtered_df = filtered_df.drop_duplicates(subset=['scenario-text'], keep='first')
without_duplicates_n = len(filtered_df)
without_duplicates_n

In [ ]:

import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Funnel(
    name = 'ACR Criteria',
    y = ['All Scenarios', 'Limit by Body Area', 'Without Pediatrics', 'Without Pregnant', 'Without IR', 'Without Monitoring<br>("Staging", "Screen", "Surveillance")', 'Without Duplicate Scenarios'],
    x = [len(df), body_area_n, without_peds_n, without_pregnant_n, without_IR_n, without_monitoring_n, without_duplicates_n],
    textinfo = "value+percent initial"
))

fig.update_layout(
    title = "ACR Criteria Funnel Analysis",
    showlegend = True,
    width = 800,
    height = 500
)

fig.show()

In [ ]:
removed_df = df[~df.index.isin(filtered_df.index)]
len(removed_df)

In [ ]:

# with pd.ExcelWriter('category_analysis.xlsx') as writer:
#     filtered_df.to_excel(writer, sheet_name='Filtered Rows', index=False)
#     removed_df.to_excel(writer, sheet_name='All Removed Rows', index=False)

In [ ]:
filtered_df.head()

Questions to answer, for each scenario, does the ACR recommend?
- No imaging (all studies are rated as “usually not appropriate”)
- CT is the ONLY “usually appropriate” imaging
- CT and other modalities are “usually appropriate” imaging (“alternatives to CT possible”)
- CT not “usually appropriate”
    - CT is “may be appropriate”
    - CT “usually not appropriate”

In [ ]:

# Create empty dataframe to store all scenario studies
all_scenario_studies = pd.DataFrame()

for index, scenario in filtered_df.iterrows():
    # Get all studies for this scenario
    scenario_studies = studies[studies['scenario-id'] == scenario['scenario-id']]
    
    # # Add scenario ID and text to each row
    # scenario_studies.insert(0, 'scenario-text', scenario['scenario-text'])
    # scenario_studies.insert(0, 'scenario-id', scenario['scenario-id'])
    
    # Append to the combined dataframe
    all_scenario_studies = pd.concat([all_scenario_studies, scenario_studies], ignore_index=True)



# Write dataframe to Excel file
# all_scenario_studies.to_excel('scenario_studies.xlsx', index=False)

In [ ]:

for index, scenario in filtered_df.iterrows():
    # Get all studies for this scenario
    scenario_studies = studies[studies['scenario-id'] == scenario['scenario-id']]
    
    # Check if any CT procedures are usually appropriate
    ct_studies = scenario_studies[
        (scenario_studies['procedure'].str.startswith('CT', na=False)) & 
        (scenario_studies['appropriateness'] == 'Usually appropriate')
    ]
    filtered_df.at[index, 'ct_usually_appropriate'] = len(ct_studies) > 0
    
    # Check if any CT procedures are may be appropriate
    ct_studies = scenario_studies[
        (scenario_studies['procedure'].str.startswith('CT', na=False)) & 
        (scenario_studies['appropriateness'] == 'May be appropriate')
    ]
    filtered_df.at[index, 'ct_may_be_appropriate'] = len(ct_studies) > 0

    # Check if any CT procedures are NOT appropriate
    ct_inappropriate_studies = scenario_studies[
        (scenario_studies['procedure'].str.startswith('CT', na=False)) & 
        (scenario_studies['appropriateness'] == 'Usually not appropriate')
    ]
    filtered_df.at[index, 'ct_not_appropriate'] = len(ct_inappropriate_studies) > 0
    
    # Are non CT studies usually appropriate?
    non_ct_studies = scenario_studies[
        (~scenario_studies['procedure'].str.startswith('CT', na=False)) & 
        (scenario_studies['appropriateness'] == 'Usually appropriate')
    ]
    filtered_df.at[index, 'other_usually_appropriate'] = len(non_ct_studies) > 0

    # Are non CT studies maybe appropriate?
    non_ct_studies = scenario_studies[
        (~scenario_studies['procedure'].str.startswith('CT', na=False)) & 
        (scenario_studies['appropriateness'] == 'May be appropriate')
    ]
    filtered_df.at[index, 'other_may_be_appropriate'] = len(non_ct_studies) > 0

    # Are non CT studies NOT appropriate?
    non_ct_studies = scenario_studies[
        (~scenario_studies['procedure'].str.startswith('CT', na=False)) & 
        (scenario_studies['appropriateness'] == 'Usually not appropriate')
    ]
    filtered_df.at[index, 'other_not_appropriate'] = len(non_ct_studies) > 0

    # Check if any MR procedures are usually appropriate
    mr_studies = scenario_studies[
        (scenario_studies['procedure'].str.startswith('MR', na=False)) & 
        (scenario_studies['appropriateness'] == 'Usually appropriate')
    ]
    filtered_df.at[index, 'mr_usually_appropriate'] = len(mr_studies) > 0
    
    # Check if any MR procedures are may be appropriate
    mr_studies = scenario_studies[
        (scenario_studies['procedure'].str.startswith('MR', na=False)) & 
        (scenario_studies['appropriateness'] == 'May be appropriate')
    ]
    filtered_df.at[index, 'mr_may_be_appropriate'] = len(mr_studies) > 0

    # Check if any MR procedures are NOT appropriate
    mr_inappropriate_studies = scenario_studies[
        (scenario_studies['procedure'].str.startswith('MR', na=False)) & 
        (scenario_studies['appropriateness'] == 'Usually not appropriate')
    ]
    filtered_df.at[index, 'mr_not_appropriate'] = len(mr_inappropriate_studies) > 0

    # Check if any US procedures are usually appropriate
    us_studies = scenario_studies[
        (scenario_studies['procedure'].str.startswith('US', na=False)) & 
        (scenario_studies['appropriateness'] == 'Usually appropriate')
    ]
    filtered_df.at[index, 'us_usually_appropriate'] = len(us_studies) > 0
    
    # Check if any US procedures are may be appropriate
    us_studies = scenario_studies[
        (scenario_studies['procedure'].str.startswith('US', na=False)) & 
        (scenario_studies['appropriateness'] == 'May be appropriate')
    ]
    filtered_df.at[index, 'us_may_be_appropriate'] = len(us_studies) > 0

    # Check if any US procedures are NOT appropriate
    us_inappropriate_studies = scenario_studies[
        (scenario_studies['procedure'].str.startswith('US', na=False)) & 
        (scenario_studies['appropriateness'] == 'Usually not appropriate')
    ]
    filtered_df.at[index, 'us_not_appropriate'] = len(us_inappropriate_studies) > 0
    
    # Classify non-CT/MR/US studies

    other_modality_studies = scenario_studies[
        (~scenario_studies['procedure'].str.startswith('CT', na=False)) &
        (~scenario_studies['procedure'].str.startswith('MR', na=False)) &
        (~scenario_studies['procedure'].str.startswith('US', na=False))
    ]
    filtered_df.at[index, 'other_modality_usually_appropriate'] = len(
        other_modality_studies[other_modality_studies['appropriateness'] == 'Usually appropriate']
    ) > 0
    filtered_df.at[index, 'other_modality_may_be_appropriate'] = len(
        other_modality_studies[other_modality_studies['appropriateness'] == 'May be appropriate']
    ) > 0
    filtered_df.at[index, 'other_modality_not_appropriate'] = len(
        other_modality_studies[other_modality_studies['appropriateness'] == 'Usually not appropriate']
    ) > 0

In [ ]:

filtered_df[['ct_usually_appropriate', 'other_usually_appropriate', 'ct_may_be_appropriate', 'other_may_be_appropriate', 'ct_not_appropriate', 'other_not_appropriate']].describe()

Some type of CT study appears in almost every scenario.

In [ ]:
percentage_with_ct = filtered_df[['ct_usually_appropriate', 'ct_may_be_appropriate', 'ct_not_appropriate']].any(axis=1).mean() * 100
print(f"Percentage of scenarios where a CT study is listed as 'usually appropriate', 'may be appropriate', or 'not appropriate': {percentage_with_ct:.2f}%")

There are a number of different CT studies addressed in the ACR criteria for the included scenarios.

In [ ]:

studies[
    (studies['procedure'].str.startswith('CT', na=False)) & 
    (studies['scenario-id'].isin(filtered_df['scenario-id']))
]['procedure'].unique()

There is a high degree of overlap between the categories of "usually appropriate", "may be appropriate", and "usually inappropriate". The classification depends largely on the type of CT study. e.g. When evaluating abdominal pain, a CT with IV contrast is usually appropriate, a CT without IV contrast may be appropriate, and a CT with and without IV contrast is usually inappropriate.

**Conclusion**: The type of CT ordered matters.

In [ ]:

from matplotlib_venn import venn3
import matplotlib.pyplot as plt

# Create sets for each category
usually_appropriate = set(filtered_df[filtered_df['ct_usually_appropriate'] == 1].index)
may_be_appropriate = set(filtered_df[filtered_df['ct_may_be_appropriate'] == 1].index)
not_appropriate = set(filtered_df[filtered_df['ct_not_appropriate'] == 1].index)

# Create Venn diagram
plt.figure(figsize=(10, 10))
venn3([usually_appropriate, may_be_appropriate, not_appropriate], 
      set_labels=('CT Usually Appropriate', 'CT May Be Appropriate', 'CT Usually Not Appropriate'))
plt.title('Distribution of Scenarios by CT Appropriateness Categories')
plt.show()

Some type of CT study is classified as "usually appropriate" in 68.1% of included scenarios

In [ ]:
n_usually_appropriate = filtered_df['ct_usually_appropriate'].sum()
percentage_usually_appropriate = (n_usually_appropriate / len(filtered_df)) * 100
print(f"Number of scenarios where a CT study is usually appropriate: {n_usually_appropriate}")
print(f"Percentage of scenarios where a CT study is usually appropriate: {percentage_usually_appropriate:.2f}%")
display(filtered_df[filtered_df['ct_usually_appropriate']]['scenario-text'])

In [ ]:

filtered_df_ct_ua = filtered_df[filtered_df['ct_usually_appropriate'] == True]
n_other_appropriate = (filtered_df_ct_ua['other_usually_appropriate'] == True).sum()
percentage = (filtered_df_ct_ua['other_usually_appropriate'] == True).mean() * 100
print(f"Of records where CT is Usually Appropriate, {percentage:.1f}% (n={n_other_appropriate}) also have a non-CT study as usually appropriate")

In [ ]:

percentage_neither = len(filtered_df[(filtered_df['ct_usually_appropriate'] == False) & (filtered_df['ct_may_be_appropriate'] == False)]) / len(filtered_df) * 100
print(f"Percentage of scenarios where a CT study is neither 'usually appropriate' nor 'may be appropriate': {percentage_neither:.2f}%")
# display(filtered_df[(filtered_df['ct_usually_appropriate'] == False) & (filtered_df['ct_may_be_appropriate'] == False)])

In [ ]:

# Calculate rows where ct_usually_appropriate is True and other_usually_appropriate is False
ct_only_appropriate = filtered_df[(filtered_df['ct_usually_appropriate'] == True) & (filtered_df['other_usually_appropriate'] == False)]
num_ct_only = len(ct_only_appropriate)
pct_ct_only = (num_ct_only / len(filtered_df)) * 100

print(f"Number of cases where only CT is usually appropriate: {num_ct_only}")
print(f"Percentage of cases where only CT is usually appropriate: {pct_ct_only:.1f}%")

In [ ]:
filtered_df[(filtered_df['ct_usually_appropriate'] == False) & (filtered_df['ct_may_be_appropriate'] == False)]['scenario-text']

In [ ]:

appropriate_percentage = (
    (filtered_df['ct_usually_appropriate'] | filtered_df['ct_may_be_appropriate']).mean() * 100
)
n_usually_or_may_be_appropriate = (
    (filtered_df['ct_usually_appropriate'] | filtered_df['ct_may_be_appropriate']).sum()
)
print(f"Percentage of cases where CT is usually or may be appropriate: {appropriate_percentage:.2f}% (n={n_usually_or_may_be_appropriate})")

**Conclusion:** For the included scenarios, choosing to order a CT study may be a reasonable option.

According to the ACR, the following scenarios, it is not "usually appropriate" to order a CT study, but "may be appropriate."

In [ ]:
filtered_df[(filtered_df['ct_usually_appropriate'] == False) & (filtered_df['ct_may_be_appropriate'] == True)]['scenario-text']

According to the ACR, in the following scenarios, it is "usually not appropriate" to order any CT study.

In [ ]:
ct_not_appropriate_studies = filtered_df[(filtered_df['ct_usually_appropriate'] == False) & 
           (filtered_df['ct_may_be_appropriate'] == False) &
           (filtered_df['ct_not_appropriate'] == True)]['scenario-text']
print(len(ct_not_appropriate_studies))
print(len(ct_not_appropriate_studies) / len(filtered_df)*100)
ct_not_appropriate_studies

In the following studies, the ACR defines no studies (CT or otherwise) as "usually appropriate" or "may be appropriate".

In [ ]:

filtered_df[(filtered_df['ct_usually_appropriate'] == False) & 
           (filtered_df['ct_may_be_appropriate'] == False) & 
           (filtered_df['other_usually_appropriate'] == False) & 
           (filtered_df['other_may_be_appropriate'] == False)]['scenario-text']

In [ ]:
#
# ======================== new category analysis begins here ============================
#

In [ ]:
# green-green: True only if CT and alternative are usually appropriate

filtered_df['green-green'] = (filtered_df['ct_usually_appropriate'] == True) & \
                            (filtered_df['other_usually_appropriate'] == True)

print(f"Added 'green-green' column with {filtered_df['green-green'].sum()} True values out of {len(filtered_df)} rows")
filtered_df[filtered_df['green-green']][['scenario-text', 'ct_usually_appropriate', 'other_usually_appropriate', 'green-green']]

In [ ]:
# green-yellow: True if CT is usually appropriate but alternative is only maybe appropriate

filtered_df['green-yellow'] = (filtered_df['ct_usually_appropriate'] == True) & \
                             (filtered_df['other_usually_appropriate'] == False) & \
                             (filtered_df['other_may_be_appropriate'] == True)

print(f"Added 'green-yellow' column with {filtered_df['green-yellow'].sum()} True values out of {len(filtered_df)} rows")
filtered_df[filtered_df['green-yellow']][['scenario-text', 'ct_usually_appropriate', 'other_usually_appropriate', 'other_may_be_appropriate', 'green-yellow']]

In [ ]:
# green-red: True if CT is usually appropriate but alternative is not appropriate

filtered_df['green-red'] = (filtered_df['ct_usually_appropriate'] == True) & \
                            (filtered_df['other_usually_appropriate'] == False) & \
                            (filtered_df['other_may_be_appropriate'] == False) & \
                            (filtered_df['other_not_appropriate'] == True)

print(f"Added 'green-red' column with {filtered_df['green-red'].sum()} True values out of {len(filtered_df)} rows")
filtered_df[filtered_df['green-red']][['scenario-text', 'ct_usually_appropriate', 'other_usually_appropriate', 'other_may_be_appropriate', 'other_not_appropriate', 'green-red']]

In [ ]:
# yellow-green: True if CT is maybe appropriate but alternative is usually appropriate

filtered_df['yellow-green'] = (filtered_df['ct_usually_appropriate'] == False) & \
                             (filtered_df['ct_may_be_appropriate'] == True) & \
                             (filtered_df['other_usually_appropriate'] == True)

print(f"Added 'yellow-green' column with {filtered_df['yellow-green'].sum()} True values out of {len(filtered_df)} rows")
filtered_df[filtered_df['yellow-green']][['scenario-text', 'ct_usually_appropriate', 'ct_may_be_appropriate', 'other_usually_appropriate', 'yellow-green']]

In [ ]:
# yellow-yellow: True if CT and alternative are maybe appropriate

filtered_df['yellow-yellow'] = (filtered_df['ct_usually_appropriate'] == False) & \
                             (filtered_df['ct_may_be_appropriate'] == True) & \
                             (filtered_df['other_usually_appropriate'] == False) & \
                             (filtered_df['other_may_be_appropriate'] == True)

print(f"Added 'yellow-yellow' column with {filtered_df['yellow-yellow'].sum()} True values out of {len(filtered_df)} rows")
filtered_df[filtered_df['yellow-yellow']][['scenario-text', 'ct_usually_appropriate', 'ct_may_be_appropriate', 'other_usually_appropriate', 'other_may_be_appropriate', 'yellow-yellow']]

In [ ]:
# yellow-red: True if CT is maybe appropriate but alternative is not appropriate

filtered_df['yellow-red'] = (filtered_df['ct_usually_appropriate'] == False) & \
                            (filtered_df['ct_may_be_appropriate'] == True) & \
                            (filtered_df['other_usually_appropriate'] == False) & \
                            (filtered_df['other_may_be_appropriate'] == False) & \
                            (filtered_df['other_not_appropriate'] == True)

print(f"Added 'yellow-red' column with {filtered_df['yellow-red'].sum()} True values out of {len(filtered_df)} rows")
filtered_df[filtered_df['yellow-red']][['scenario-text', 'ct_usually_appropriate', 'ct_may_be_appropriate', 'other_usually_appropriate', 'other_may_be_appropriate', 'other_not_appropriate', 'yellow-red']]

In [ ]:
# red-green: True if CT is not appropriate but alternative is usually appropriate

filtered_df['red-green'] = (filtered_df['ct_usually_appropriate'] == False) & \
                            (filtered_df['ct_may_be_appropriate'] == False) & \
                            (filtered_df['ct_not_appropriate'] == True) & \
                            (filtered_df['other_usually_appropriate'] == True)

print(f"Added 'red-green' column with {filtered_df['red-green'].sum()} True values out of {len(filtered_df)} rows")
filtered_df[filtered_df['red-green']][['scenario-text', 'ct_usually_appropriate', 'ct_may_be_appropriate', 'ct_not_appropriate', 'other_usually_appropriate', 'red-green']]

In [ ]:
# red-yellow: True if CT is not appropriate but alternative is maybe appropriate

filtered_df['red-yellow'] = (filtered_df['ct_usually_appropriate'] == False) & \
                            (filtered_df['ct_may_be_appropriate'] == False) & \
                            (filtered_df['ct_not_appropriate'] == True) & \
                            (filtered_df['other_usually_appropriate'] == False) & \
                            (filtered_df['other_may_be_appropriate'] == True)

print(f"Added 'red-yellow' column with {filtered_df['red-yellow'].sum()} True values out of {len(filtered_df)} rows")
filtered_df[filtered_df['red-yellow']][['scenario-text', 'ct_usually_appropriate', 'ct_may_be_appropriate', 'ct_not_appropriate', 'other_usually_appropriate', 'other_may_be_appropriate', 'red-yellow']]

In [ ]:

# red-red: True only if CT and alternative are usually not appropriate and no other more appropriate studies exist
filtered_df['red-red'] = (filtered_df['ct_not_appropriate'] == True) & \
                      (filtered_df['other_not_appropriate'] == True) & \
                      (filtered_df['ct_usually_appropriate'] == False) & \
                      (filtered_df['ct_may_be_appropriate'] == False) & \
                      (filtered_df['other_usually_appropriate'] == False) & \
                      (filtered_df['other_may_be_appropriate'] == False)

print(f"\nAdded 'red-red' column with {filtered_df['red-red'].sum()} True values out of {len(filtered_df)} rows")
filtered_df[filtered_df['red-red']][['scenario-text', 'ct_usually_appropriate', 'ct_may_be_appropriate', 'other_usually_appropriate', 'other_may_be_appropriate', 'red-red']]

In [ ]:
# write out the contents of filtered_df to a CSV file

filtered_df.to_csv('filtered_scenarios_with_categories.csv', index=False)

## -- alternative breakdowns --

In [ ]:
# For each scenario where 'red-green' is True, list the non-CT studies that are 'Usually appropriate'
red_green_scenarios = filtered_df[filtered_df['red-green'] == True]

for index, scenario in red_green_scenarios.iterrows():
    scenario_id = scenario['scenario-id']
    # Get studies for this scenario
    scenario_studies = studies[studies['scenario-id'] == scenario_id]
    # Filter for non-CT, usually appropriate
    appropriate_non_ct = scenario_studies[
        (~scenario_studies['procedure'].str.startswith('CT', na=False)) & 
        (scenario_studies['appropriateness'] == 'Usually appropriate')
    ]
    print(f"Scenario ID {scenario_id}: {list(appropriate_non_ct['procedure'])}")

In [ ]:
import matplotlib.pyplot as plt

# Count the number of scenarios in each category
num_green_green = filtered_df['green-green'].sum()
num_green_yellow = filtered_df['green-yellow'].sum()
num_green_red = filtered_df['green-red'].sum()
num_yellow_green = filtered_df['yellow-green'].sum()
num_yellow_yellow = filtered_df['yellow-yellow'].sum()
num_yellow_red = filtered_df['yellow-red'].sum()
num_red_green = filtered_df['red-green'].sum()
num_red_yellow = filtered_df['red-yellow'].sum()
num_red_red = filtered_df['red-red'].sum()

# Create a 3x3 grid
fig, axes = plt.subplots(3, 3, figsize=(10, 10))

# Row labels
row_labels = ['CT Usually Appropriate', 'CT May Be Appropriate', 'CT Usually Not Appropriate']
# Column labels
col_labels = ['Alternatives Usually Appropriate', 'Alternatives May Be Appropriate', 'Alternatives Usually Not Appropriate']

# Data for each cell
data = [
    [num_green_green, num_green_yellow, num_green_red],
    [num_yellow_green, num_yellow_yellow, num_yellow_red],
    [num_red_green, num_red_yellow, num_red_red]
]

# Plot each cell
for i in range(3):
    for j in range(3):
        ax = axes[i, j]
        ax.text(0.5, 0.5, str(data[i][j]), fontsize=20, ha='center', va='center')
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.set_xticks([])
        ax.set_yticks([])
        ax.set_title(f'{row_labels[i]}\n{col_labels[j]}', fontsize=12)

plt.tight_layout()
plt.show()

In [ ]:
modality_cols = ['mr_usually_appropriate', 'us_usually_appropriate', 'other_modality_usually_appropriate']
modality_labels = ['MR', 'US', 'Other']
colors = ['#ff7f0e', '#2ca02c', '#d62728']

category_cols = ['green-green', 'yellow-green', 'red-green']
titles = [
    'CT Usually Appropriate\n& Alternative Usually Appropriate',
    'CT May Be Appropriate\n& Alternative Usually Appropriate',
    'CT Usually Not Appropriate\n& Alternative Usually Appropriate'
]

fig, axes = plt.subplots(1, 3, figsize=(16, 5), sharey=True)

for j, col in enumerate(category_cols):
    subset = filtered_df[filtered_df[col] == True]
    total_count = len(subset)
    percentages = subset[modality_cols].mean().mul(100) if total_count > 0 else pd.Series([0, 0, 0], index=modality_cols)

    ax = axes[j]
    ax.bar(modality_labels, percentages, color=colors)
    ax.set_title(titles[j], fontsize=11)
    ax.text(0.5, 0.92, f'n={total_count}', transform=ax.transAxes, ha='center', va='top', fontsize=12)
    ax.set_ylim(0, 100)
    if j == 0:
        ax.set_ylabel('% scenarios with modality usually appropriate')
    ax.set_xticks(range(len(modality_labels)))
    ax.set_xticklabels(modality_labels, rotation=0)

    for k, val in enumerate(percentages):
        ax.text(k, val + 2, f'{val:.0f}%', ha='center', va='bottom', fontsize=8)

plt.tight_layout()
plt.show()